### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'append' when running predict.py

### ISSUE THREAD

**Issue by ZJURenyi** [skandlab/VarNet#4]
Hello,

I got this error when I run the pipeline
```
Sample Output: varnet/TAR077_T

Candidates Directory: varnet/TAR077_T/candidates

Reading bed file: /hpctmp/renyi04/reference/bed/Agilent_SureSelect_v6_r2_hg38_Padded.bed
Candidates file: varnet/TAR077_T/candidates/snvs/Positions.csv
Candidates file: varnet/TAR077_T/candidates/indels/Positions.csv
============== FILTERING REGIONS COMPLETE ===============
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_11.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_11.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_37.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_37.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_59.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_59.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_83.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_83.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_109.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_109.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_15.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_15.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_43.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_43.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_63.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_63.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_86.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_86.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_17.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_17.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_42.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_42.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_64.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_64.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_88.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_88.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_16.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_16.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_46.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_46.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_68.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_68.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_92.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_92.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_22.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_22.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_41.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_41.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_66.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_66.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_90.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_90.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_18.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_18.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_35.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_35.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_62.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_62.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_87.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_87.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_3.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_3.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_38.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_38.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_67.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_67.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_91.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_91.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_2.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_2.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_44.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_44.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_69.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_69.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_94.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_94.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_14.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_14.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_40.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_40.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_65.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_65.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_89.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_89.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_21.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_21.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_25.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_25.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_48.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_48.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_72.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_72.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_98.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_98.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_4.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_4.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_47.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_47.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_70.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_70.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_93.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_93.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_1.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_1.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_24.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_24.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_49.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_49.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_75.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_75.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_104.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_104.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_6.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_6.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_34.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_34.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_50.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_50.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_74.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_74.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_99.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_99.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_12.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_12.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_45.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_45.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_71.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_71.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_95.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_95.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_10.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_10.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_36.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_36.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_52.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_52.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_73.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_73.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_101.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_101.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_19.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_19.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_26.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_26.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_61.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_61.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_80.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_80.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_97.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_97.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_8.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_8.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_39.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_39.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_54.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_54.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_81.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_81.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_103.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_103.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_23.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_23.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_33.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_33.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_53.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_53.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_76.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_76.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_102.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_102.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_13.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_13.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_32.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_32.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_51.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_51.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_79.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_79.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_96.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_96.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_7.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_7.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_31.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_31.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_60.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_60.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_84.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_84.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_100.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_100.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_20.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_20.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_27.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_27.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_57.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_57.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_78.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_78.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_105.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_105.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_0.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_0.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_28.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_28.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_56.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_56.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_77.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_77.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_108.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_108.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_5.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_5.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_29.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_29.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_55.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_55.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_85.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_85.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_107.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_107.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_9.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_9.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_30.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_30.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_58.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_58.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_82.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_82.csv')
('COMPLETED SNV BATCH: ', 'varnet/TAR077_T/candidates/snvs/batch_106.csv')
('COMPLETED INDEL BATCH', 'varnet/TAR077_T/candidates/indels/batch_106.csv')
('Number of SNV candidates: ', 61462)
('SNV PREDICTION BATCH:', 0)
1/1 [==============================] - ETA: 0s('SNV PREDICTION BATCH:', 14)
1/1 [==============================] - ETA: 0s('SNV PREDICTION BATCH:', 2)
1/1 [==============================] - ETA: 0s('SNV PREDICTION BATCH:', 20)
1/1 [==============================] - 20s 20s/step
('SNV PREDICTION BATCH:', 10)
1/1 [==============================] - 20s 20s/step
('SNV PREDICTION BATCH:', 5)
1/1 [==============================] - ETA: 0s('SNV PREDICTION BATCH:', 1)
1/1 [==============================] - ETA: 0s('SNV PREDICTION BATCH:', 8)
1/1 [==============================] - 20s 20s/step
('SNV PREDICTION BATCH:', 13)
1/1 [==============================] - ETA: 0s('SNV PREDICTION BATCH:', 18)
1/1 [==============================] - 20s 20s/step
('SNV PREDICTION BATCH:', 23)
1/1 [==============================] - 20s 20s/step
('SNV PREDICTION BATCH:', 19)
1/1 [==============================] - 20s 20s/step
('SNV PREDICTION BATCH:', 22)
1/1 [==============================] - 20s 20s/step
('SNV PREDICTION BATCH:', 17)
1/1 [==============================] - 20s 20s/step
('SNV PREDICTION BATCH:', 7)
1/1 [==============================] - 20s 20s/step
('SNV PREDICTION BATCH:', 16)
1/1 [==============================] - 20s 20s/step
('SNV PREDICTION BATCH:', 6)
1/1 [==============================] - 20s 20s/step
('SNV PREDICTION BATCH:', 12)
1/1 [==============================] - 20s 20s/step
('SNV PREDICTION BATCH:', 4)
1/1 [==============================] - 20s 20s/step
('SNV PREDICTION BATCH:', 11)
1/1 [==============================] - 20s 20s/step
('SNV PREDICTION BATCH:', 3)
1/1 [==============================] - 20s 20s/step
('SNV PREDICTION BATCH:', 21)
1/1 [==============================] - 20s 20s/step
('SNV PREDICTION BATCH:', 9)
1/1 [==============================] - 20s 20s/step
('SNV PREDICTION BATCH:', 15)
1/1 [==============================] - 21s 21s/step
('SNV PREDICTION BATCH:', 41)
1/1 [==============================] - 0s 497ms/step
('SNV PREDICTION BATCH:', 33)
1/1 [==============================] - 1s 693ms/step
('SNV PREDICTION BATCH:', 38)
1/1 [==============================] - 1s 698ms/step
('SNV PREDICTION BATCH:', 32)
1/1 [==============================] - 1s 836ms/step
('SNV PREDICTION BATCH:', 45)
1/1 [==============================] - 1s 632ms/step
('SNV PREDICTION BATCH:', 46)
1/1 [==============================] - 1s 833ms/step
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/svu/renyi04/.conda/miniconda/4.9/envs/varnet/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 436, in _process_worker
    r = call_item()
  File "/home/svu/renyi04/.conda/miniconda/4.9/envs/varnet/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 288, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/svu/renyi04/.conda/miniconda/4.9/envs/varnet/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/svu/renyi04/.conda/miniconda/4.9/envs/varnet/lib/python3.10/site-packages/joblib/parallel.py", line 263, in __call__
    return [func(*args, **kwargs)
  File "/home/svu/renyi04/.conda/miniconda/4.9/envs/varnet/lib/python3.10/site-packages/joblib/parallel.py", line 263, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/svu/renyi04/modules/VarNet-1.1.0/snvs/predict.py", line 191, in predict_snvs
    results = results.append(results_dict, ignore_index = True)
  File "/home/svu/renyi04/.conda/miniconda/4.9/envs/varnet/lib/python3.10/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/svu/renyi04/modules/VarNet-1.1.0/predict.py", line 521, in <module>
    main()
  File "/home/svu/renyi04/modules/VarNet-1.1.0/predict.py", line 420, in main
    Parallel(n_jobs=int(args.processes))( delayed(predict_snvs)(batch, idx, args, snv_predictions_folder) for idx, batch in enumerate(snv_candidate_batches) )
  File "/home/svu/renyi04/.conda/miniconda/4.9/envs/varnet/lib/python3.10/site-packages/joblib/parallel.py", line 1061, in __call__
    self.retrieve()
  File "/home/svu/renyi04/.conda/miniconda/4.9/envs/varnet/lib/python3.10/site-packages/joblib/parallel.py", line 938, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/svu/renyi04/.conda/miniconda/4.9/envs/varnet/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/svu/renyi04/.conda/miniconda/4.9/envs/varnet/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/home/svu/renyi04/.conda/miniconda/4.9/envs/varnet/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
AttributeError: 'DataFrame' object has no attribute 'append'
```

my code is here
```
        python /home/svu/renyi04/modules/VarNet-1.1.0/filter.py \
            --sample_name TAR077_T \
            --normal_bam 4.BAM/TAR077_N_dedup_bqsr.bam \
            --tumor_bam 4.BAM/TAR077_T_dedup_bqsr.bam \
            --processes 24 \
            --output_dir varnet \
            --reference ${ref_fa} \
            --region_bed ${bed}

        python /home/svu/renyi04/modules/VarNet-1.1.0/predict.py \
            --sample_name TAR077_T \
            --normal_bam 4.BAM/TAR077_N_dedup_bqsr.bam \
            --tumor_bam 4.BAM/TAR077_T_dedup_bqsr.bam \
            --processes 24 \
            --output_dir varnet \
            --reference ${ref_fa}
```

Here are the output when pipeline stopped
```
└── TAR077_T
    ├── candidates
    │   ├── indels
    │   │   └── Positions.csv
    │   └── snvs
    │       └── Positions.csv
    └── predictions
        └── snvs
```

Do you have any suggestion on how to fix it?

Thank you!
Ren Yi

**Comment by kiranchari** [comment]
Hi Ren Yi,

Could you try downgrading pandas to 1.X? Looks like you are using pandas 2.0.

pandas DataFrame's append method was deprecated in v2.0: https://pandas.pydata.org/docs/whatsnew/v2.0.0.html#deprecations

You can see VarNet's package requirements here: https://github.com/skandlab/VarNet/blob/main/requirements.txt

**Comment by ZJURenyi** [comment]
> Hi Ren Yi,
> 
> Could you try downgrading pandas to 1.X? Looks like you are using pandas 2.0.
> 
> pandas DataFrame's append method was deprecated in v2.0: https://pandas.pydata.org/docs/whatsnew/v2.0.0.html#deprecations
> 
> You can see VarNet's package requirements here: https://github.com/skandlab/VarNet/blob/main/requirements.txt

Thank you! Downgrading pandas worked!
